import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Image
                src="/client-5.png"
                alt="logo"
                className={styles.vercelLogo}
                width={300}
                height={100}
                priority
              />
          <div>
              <Image
                className={styles.logo}
                src="/hero-img.png"
                alt="Banner"
                width={400}
                height={300}
                priority
              />
          </div>
        </div>

      <div className={styles.center}>
         <h1 className="cover-heading">HELLO WORLD!</h1>
      </div>

        <div className={styles.grid}>
          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image 
              className={styles.logo}
              src="/team-1.jpg"
              alt="Founder"
              width={230}
              height={230}
              priority/>

            <h2>
              Founder <span>-&gt;</span>
            </h2>
            <p>
            Innovative and visionary individual dedicated to revolutionizing &nbsp;online experiences through cutting-edge technology.
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image 
              className={styles.logo}
              src="/team-2.jpg"
              alt="Content Creator"
              width={230}
              height={230}
              priority/>
            <h2>
              Content Creator<span>-&gt;</span>
            </h2>
            <p>
            Curates engaging, relevant, and &nbsp;high-quality content for a website, catering to the needs and interests of the target audience.
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
             <Image 
              className={styles.logo}
              src="/team-3.jpg"
              alt="SEO Specialist"
              width={230}
              height={230}
              priority/>
            <h2>
            SEO Specialist<span>-&gt;</span>
            </h2>
            <p>
            Optimizes website content and structure to enhance its &nbsp;visibility in search engine results, driving organic traffic and improving online presence..
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image 
              className={styles.logo}
              src="/team-4.jpg"
              alt="Digital Marketer"
              width={230}
              height={230}
              priority/>
            <h2>
            Digital Marketer<span>-&gt;</span>
            </h2>
            <p>
            Analyze to develop and implement effective marketing campaigns,&nbsp; 
            driving engagement, conversions, and growth for businesses in the digital landscape..
            </p>
          </a>
    </div>
      </main>
    </>
  )
}
